# Generated by Django 5.1.6 on 2025-07-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Заголовок страницы для SEO (тег title)",
                        max_length=255,
                        verbose_name="Мета-заголовок",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание страницы для SEO (мета-тег description)",
                        verbose_name="Мета-описание",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        help_text="Ключевые слова через запятую для SEO (мета-тег keywords)",
                        max_length=255,
                        verbose_name="Ключевые слова",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Содержание")),
            ],
            options={
                "verbose_name": "Главная страница",
                "verbose_name_plural": "Главная страница",
            },
        ),
    ]
